### ISSUE TITLE
landing-page v2 integration

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#1005]
This is an tracking issue for page and content integration for our landing-page.

```[tasklist]
### Pages
- [ ] https://github.com/helpwave/web/issues/1012
- [ ] https://github.com/helpwave/web/issues/1009
- [ ] https://github.com/helpwave/web/issues/1008
- [ ] https://github.com/helpwave/web/issues/1051
- [ ] https://github.com/helpwave/web/issues/1052
```
