### ISSUE TITLE
Tasks product page `/product/tasks`

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#1009]
```[tasklist]
### Tasks
- [ ] https://github.com/helpwave/web/issues/1006
- [ ] https://github.com/helpwave/web/issues/1011
- [ ] https://github.com/helpwave/web/issues/1010
```
![Products - tasks](https://github.com/helpwave/web/assets/40192999/78821d0d-3a48-4ceb-b686-0383347ea48c)
