### ISSUE TITLE
Task template overview

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#108]
```[tasklist]
### Task template overview
- [ ] #106
- [ ] #107
- [ ] https://github.com/helpwave/web/issues/318
- [ ] https://github.com/helpwave/web/issues/319
- [ ] https://github.com/helpwave/web/issues/363
- [ ] #364
- [ ] https://github.com/helpwave/web/issues/393
```

**Comment by use-to** [comment]
![Tasks - overview of wards in an organization](https://user-images.githubusercontent.com/13922835/235242875-dc244fc6-e207-4b45-8b1d-0b667bc5ff4a.jpg)

**Comment by use-to** [comment]
![Tasks - overview of Task Template in a wards](https://user-images.githubusercontent.com/13922835/235242908-95fe7792-aecb-4763-8e7a-07664121da86.jpg)

**Comment by use-to** [comment]
As for now, all tracked issues have been merged.
Thanks to @DasProffi and @rajarshisamaddar
