### ISSUE TITLE
Input disclaimer

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#392]
All of our components where the user can input arbitrary text should provide something like an "input hint". The input hint text should only visible when the user is about to use the input element. In the future, we will use this input element to indicate sensitive fields where the user should not enter patient data.

```[tasklist]
### Implementing input hint
- [ ] [Input.tsx](https://github.com/helpwave/web/blob/main/lib/components/user_input/Input.tsx)
- [ ] [Textare.tsx](https://github.com/helpwave/web/blob/main/lib/components/user_input/Input.tsx)
- [ ] Adopting "input hint" for tasks
```

![Bildschirm­foto 2023-05-11 um 10 48 42 PM](https://github.com/helpwave/web/assets/40192999/58b2d3b7-e8e4-460b-86ec-860409dc4d61)
