### ISSUE TITLE
Marry frontend and backend

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#460]
This issue is tracking the progress of the integration of the API. Right now, we are using DTOs and Mocks across `helpwave/web/tasks`. In the end, we should fully CRUD on all relevant entities.

```[tasklist]
### Tasks
- [ ] https://github.com/helpwave/web/issues/466
- [ ] https://github.com/helpwave/web/issues/467
- [ ] https://github.com/helpwave/web/issues/468
- [ ] https://github.com/helpwave/web/issues/470
- [ ] https://github.com/helpwave/web/issues/476
- [ ] https://github.com/helpwave/web/issues/482
- [ ] https://github.com/helpwave/web/issues/477
- [ ] https://github.com/helpwave/web/issues/479
- [ ] https://github.com/helpwave/web/issues/480
- [ ] https://github.com/helpwave/web/issues/481
- [ ] https://github.com/helpwave/web/issues/478
- [ ] https://github.com/helpwave/web/issues/499
- [x] Update task status handling on kanban
- [ ] https://github.com/helpwave/web/issues/510
- [ ] https://github.com/helpwave/web/issues/496
- [ ] https://github.com/helpwave/web/issues/509
- [ ] https://github.com/helpwave/web/issues/642
```
