### ISSUE TITLE
Internationalization finishing touches

### ISSUE THREAD

**Issue by JannikWibker** [helpwave/web#62]
There were a few things still missing in PR #61, these will be addressed here:

- [ ] a few translations here and there
- [ ] layout fixes where different translations have given elements different sizes per language
- [ ] language switching using some kind of UI
- [ ] persisting language choices
